### PR TITLE
Use github.com/ankicommunity/anki-sync-server

### PR DESCRIPTION
**Pull request by levindu**
Hi, this is an attempt to use the lastest `github.com/ankicommunity/anki-sync-server` code.

I'm able to sync successfully with Anki 2.1.35 (Arch Linux).

Having problem pip install anki 2.1.35 with Alpine, I switch to using Debian Buster. To reduce the image size, multi stage building is used. The resulting image size is 161MB.

Pip install with anki 2.1.36 is not possible in the Debian Buster image, and the requirements.txt from anki-sync-server has noisy lines which pip complains. Therefore, a patch is needed for that file, which is stated in the README.md.

### CODE REVIEW

**Comment by kuklinistvan** [comment]
Hello,

thank you for your pull request! I'm kindly asking you for your patience, I'll get back to you :)

**Review by VikashKothary — APPROVED** [review]
Looks good to me. Thanks so much for your contribution.

There are a few issues but nothing that's a blocker. I'm happy to merge the PR then create separate issues for the issues because this imo is a critical issue. 

@kuklinistvan Let me know what you think.

**Comment by kuklinistvan** [comment]
Hello,
Thank you very much for looking at the PR. I have only one remark in general: I think we need a way to mark which is the released, tested, production-ready state.
@VikashKothary, what do you think, should we create another develop branch, or let only the tags themselves indicate the releases? Excuse me if we have discussed this already and I've missed it.

**Comment by VikashKothary** [comment]
Yh exactly. I don't consider that a blocker for this ticket but it is a good question. I think part of the solution is the use of LABELs in PR #12. But also the use of Dockerfile versioning. Maybe it's worth open a ticket to discuss it?

In the mean time, I think I'll merge this because it is a high demand update.

**Comment by valuex** [comment]
@kuklinistvan Can you help to update the docker version at https://registry.hub.docker.com/r/kuklinistvan/anki-sync-server/?
It seems that this pull request has not been uploaded to docker hub. Thanks.

**Comment by VikashKothary** [comment]
Hi @valuex, there is a issue open for that. See https://github.com/ankicommunity/anki-devops-services/issues/11. There's only a minor change that needs to be made in our CI/CD pipeline and we should then have the latest image on DockerHub.

**Comment by kuklinistvan** [comment]
Hey there! Sorry, it is the sixth week of the semester and I feel overloaded already. If it is a permission problem that I can fix, let me know!

**Comment by VikashKothary** [comment]
Hi @kuklinistvan, don't worry. It's not a permission issue. 

We're in the process of uploading tthe docker images to a new `ankicommunity` org. There's just an open issue which prevents the CI from doing so. We're in the process of fixing it.

Good luck with your exams!

**Comment by kuklinistvan** [comment]
@VikashKothary Thank you :)

**Pull request merged**
