### PR TITLE
Use dotenv files to configure the services using environment variables

### LINKED ISSUE #3: Use Environment Variables
We should remove https://github.com/ankicommunity/docker-anki-sync-server/blob/master/Docker/config/ankisyncd.conf.example and use environment variables (https://github.com/ankicommunity/anki-sync-server#envvar-configuration-overrides) instead. 

This will simplify the build and more familiar to Docker users. This will be the preferred method of configuration in the future. Thoughts?

### PR DESCRIPTION
**Pull request by VikashKothary**
Resolves #3 
Also mentioned in #18.

### CODE REVIEW

**Review by AntonOfTheWoods — COMMENTED** [review]
This looks to mainly be docker-compose-related, and I have no real experience with docker-compose, nor any possibility to have any, given my immediate-long term time commitments and the absence of utility it brings to me.

**Comment by VikashKothary** [comment]
It'll apply to all of the above from docker, docker-compose, the software and build scripts. But that'll come in the next few PRs.

**Comment by kuklinistvan** [comment]
Looks good to me at first glance - but I could not examine it thoroughly.

**Review by kuklinistvan — APPROVED** [review]
Found the button :)

**Pull request merged**
